notifications:
  email: false
  slack:
    rooms:
      secure: E2WCIbmn7S32BRfTODPI8y3p/cyQSmC3M3PFKdJARshoYsuArxuliHa57R4feIderPpbZnAiGv7WLWuL32rSR2nxZnv6KL9syrUhDct/Ak2RTNT8hTY0VeF17tK3fvQ+U2N65InVB6oHucW1PzFTPGKF8GYgarBATGNRuX/MQ0c2wnkXV8VFGTUNu39v1Z0ZcFEVLa2G/avIplPnPQykkxPA3Hoc0o/mBhDq5AStzPoAHQFWfnYzDJE/UGlqTl8j8D2F2iWlB5zDXlb9NoBHR+4YfAEsAyEuXC32ONhdw1KwuQfioZ9Y58fUQ8XC3COVRsvlFpZswzKdcqA9MUsX46mZZGjerQZPth2VNAHD26BxO3rvMFWAy32vlc3q78DVHz5VEteiD5KBWVYec7AU2gU3hE3s89v9YXOcMjPBOfzBwbSiyuz8wNeu+IUUH6mY0nuMEUHUFP9TnbspzDCcVHIqbSwcVsYVh+4YeAFKJ1FJh0TzXPLIHIF5PhjK6XsDvLS/frYKWQyfsKv/R4ciSI0XA4ZfYKaVqu+O2zoZUlWsPxF3TBJyjpCE9JpViMmVpyQ9G8VQLlsZVMuDKmRaHjzoBm6tG3F5yetNH8CD4855VH6PuuHgICsOl/IeZ1v9HtaWyjtok4Rf84yfDKEl0JZRQaUZ/rlIRdjhZ43twTI=
    on_success: always
    on_failure: always 
        
jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true #skip default installation
    script:
    - docker-compose -f docker-compose.yml up -d
    - docker cp kapp:/opt/kapp/dist dist
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
    - docker push kalisio/kapp
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: kapp-builds
      local_dir: dist
      upload_dir: "$TRAVIS_BUILD_NUMBER"

  - stage: TEST
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 0c731245ebc783e72b0ac56a58e7e9bc8b01550754ff01301212b3f32ac98dcb
    install:
    - docker pull kalisio/kapp
    script:
    - docker-compose -f docker-compose.yml up -d mongodb-kapp
    - docker-compose -f docker-compose.yml -f docker-compose.server-tests.yml up kapp
    - docker-compose -f docker-compose.yml -f docker-compose.client-tests.yml up -d kapp
    - docker-compose -f docker-compose.yml -f docker-compose.client-tests.yml up testcafe
    - codeclimate-test-reporter < server-coverage/lcov.info
    before_script:
    - npm install -g codeclimate-test-reporter
    after_script:
    - docker-compose down -v
    
  - stage: ANDROID
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-27.0.2
      - android-27
      - extra
    before_install:
    - nvm install 8
    - yes | sdkmanager "platforms;android-27"
    - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar -C ./cordova
    install:
    - pip install --user awscli
    - npm install -g cordova
    - gem install fastlane
    script:
    - aws s3 sync s3://kapp-builds/$TRAVIS_BUILD_NUMBER www
    - cd cordova
    - cordova platform add android
    - cordova build --release
    - fastlane deploy
    


