notifications:
  email: false
  slack:
    rooms:
      secure: sP096KaVHWWlU7fJHF0A2HpovkcuiBX0vrESM3lZgzHZS01ihKwUx+PKvsLNXBUi9QHOCWeBB20ZO7gGIly8SGV/5AysLjyuhtNBTjnzxPAr54yctAdkai2u/v7eiSpAdCf2+SORljcqbsRlcgSjrRIsuCU1BtIBmIDq9qv2XzxUnOmrtiSQOxhYkwYIfhvd9QRvbLSDI3Wm4DAXjMRsrEneiWh58uHLaUTJyWIOvzCCM9bmh5rM6H9PTCx4/KZnmwI1SAsoTpTnq5f3rybf7L6gR41pMO5f7ZHipKKOzyeHxtKuRTWrgbfEw477gvVoYaEGSBBA8zFcLpNLkc5f8rGUq5AcRXdaynV4Q9JygmiKd/2SHx4ik0QKLu2iwXn0n6X05F9WANYhUzhFlYZMGd2QB2WFNh3hA9IeB5GgSmxnYvji4OjtWBzMZVUA+H3SsTaSidNb2/aEWrflI99ojr0B0aMnLFRoGKMSyxR5x5yLTDIaW/7qjjoHCkbimot/f4MKspZzehMcKWv9ZwwkNXffiUMVla7R3QGyz/9qBaduavNrT+j0Tm5xaGhDd3/Vn8MvvqHqDy7eqMcq4cdNhW3uSj0OtyyO3Jt6WpkGrQ5ewHxpQoou7q9GDVwTMIiZE+p5e0lc/zCmepV9K2zGYwo0Dp+mqR0qwr7+UFxTFqk=
    on_success: always
    on_failure: always
stages:
- name: APP
  if: commit_message !~ /(skip[ _-]app)/
- name: DOC
  if: commit_message =~ /\[build doc\]/
jobs:
  include:
  - stage: APP
    os: linux
    language: node_js
    node_js:
    - '16'
    services:
    - docker
    install: skip
    before_script:
    - export -f travis_fold
    script:
    - bash .travis.app.sh
  - stage: DOC
    os: linux
    language: node_js
    node_js:
    - '18.14.1'
    install: true
    script: bash .travis.doc.sh
    deploy:
      provider: pages
      local-dir: docs/.vitepress/dist
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      on:
        branch: master
