language: node_js
node_js:
  - '8'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '0c731245ebc783e72b0ac56a58e7e9bc8b01550754ff01301212b3f32ac98dcb'
notifications:
  email: false
before_install:
  - npm install -g quasar-cli
install:
  - npm install
  - quasar build
  - cd api
  - npm install
  - npm run build
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g quasar-cli
  - git clone https://github.com/kalisio/kCore.git && cd kCore && yarn install && yarn link && cd .. && yarn link kCore
  - git clone https://github.com/kalisio/kTeam.git && cd kTeam && yarn install && yarn link && cd .. && yarn link kTeam
  - git clone https://github.com/kalisio/kNotify.git && cd kNotify && yarn install && yarn link && cd .. && yarn link kNotify
after_script:
  - codeclimate-test-reporter < api/coverage/lcov.info

