stages:
- BUILD
- TEST
#- ANDROID
#- IOS

jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 0c731245ebc783e72b0ac56a58e7e9bc8b01550754ff01301212b3f32ac98dcb
    script:
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
    - docker-compose build
    - docker push kalisio/kapp
    
  - stage: TEST
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    script:
    - docker-compose -f docker-compose.yml up -d mongodb-kapp
    - docker-compose -f docker-compose.yml -f docker-compose.server-tests.yml up kapp
    - docker-compose -f docker-compose.yml -f docker-compose.client-tests.yml up -d kapp
    - docker-compose -f docker-compose.yml -f docker-compose.client-tests.yml up testcafe
    before_script:
    - npm install -g codeclimate-test-reporter
    after_script:
    - codeclimate-test-reporter < server-coverage/lcov.info
    - docker-compose down -v

