notifications:
  email: false
  slack:
    rooms:
      secure: 2wRukOpqNxWDcrPyntSXFEP/mMXIfvGKL2rAJSKsaUzEppABWxf3zoa66mdP5uC1MI6yndmirSr+0OR0KDxpOp0YytxydziSBtZYJTFKiyqsK8tzben47nP/lOrYJn5+3Vc4EIyVyAd1Jr+3M2g2wuG4/4yanPCJmrkBLDq/T7BsbHUgAU3IIuUQoFDh6BJ+HtEgprRVt1YSCDLMS9MEenvprRX3SZ88zeJZctxUe/10WhqidszLEM3r0vCXutYNiHACnaJjE/CBAL/36KMkucpjekKg0CBr3avvqPZDy8L5p87/HIPJGYHDw17TLwNG0IhlZuISSSGeL0MzY0ChTgmtZDRWWZOAtaSg5CM3SP3VQffgPv/JEyPMxtDBnWZALrt/J8iK8CqmmSncnkROi2EiJ3c5lA2U786PAwHvLCrG/CHTv9MvSmzualUxY/+a9DwqAFwBRnrBWyPWOv4/BqpZepO3LDL3GUpAC/r2w+vTYZQw/SRmR6yT4dAgHXVqvINdVhWvJnOiX7s3jaQe6DCzMSb1rTJhYyXwILnkpgVf7AsyJXQrr3rAz/KKaYCNY43/Q0bNRJmmN2QTD+kICNmQMJiWogeiJ2NfylFzU0fK66BE7LYV0GJUHB2G9SzEHmls5Ej1A86zA34yyWagQEg7AxSLMOwFfckGEh0d9JU=
    on_success: always
    on_failure: always
    
stages:
- name: BUILD
- name: TEST
- name: DEPLOY
jobs:
  include:
  - stage: BUILD
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true
    script:
    - bash travis.build.sh
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: kano-builds
      local_dir: dist
      upload_dir: "$TRAVIS_BUILD_NUMBER/dist"
      on:
        all_branches: true
  - stage: TEST
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    addons:
      code_climate:
        repo_token: 30d4aec026718918864f0293f71801bef5922e57200e1901e174e1bde1562fcc
    install:
    - npm install -g codeclimate-test-reporter
    script:
    - bash travis.test.sh
    after_script:
    - codeclimate-test-reporter < server-coverage/lcov.info
    deploy:
    - provider: s3
      skip_cleanup: true
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: kano-builds
      local_dir: server-coverage
      upload_dir: "$TRAVIS_BUILD_NUMBER/server-tests/coverage"
      on:
        all_branches: true
    - provider: s3
      skip_cleanup: true
      access_key_id: "$S3_ACCESS_KEY"
      secret_access_key: "$S3_SECRET_ACCESS_KEY"
      bucket: kano-builds
      local_dir: client-screenshots
      upload_dir: "$TRAVIS_BUILD_NUMBER/client-tests/screenshots"
      on:
        all_branches: true
  - stage: DEPLOY
    language: node_js
    node_js:
    - '8'
    services:
    - docker
    install: true
    script:
    - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
      -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    deploy:
      provider: script
      skip_cleanup: true
      script: bash travis.deploy.sh
      on:
        all_branches: true
