version: '3'

services:
  kapp:
    build:
      context: .
      dockerfile: ./dockerfile.${FLAVOR}
    container_name: kapp
    image: kalisio/kapp
    depends_on:
      - mongodb-kapp
    links:
      - mongodb-kapp:mongodb
    ports:
      - 8081:8081
    environment:
      - GOOGLE_MAIL_USER
      - GOOGLE_MAIL_PASSWORD
      - GOOGLE_USER
      - GOOGLE_PASSWORD
      - GITHUB_USER
      - GITHUB_PASSWORD
      - SNS_ACCESS_KEY
      - SNS_SECRET_ACCESS_KEY
      - SNS_ANDROID_ARN
      - S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - NODE_APP_INSTANCE=${FLAVOR}
      - DB_URL=mongodb://mongodb:27017/kApp
    networks:
      - kapp
  mongodb-kapp:
    container_name: mongodb-kapp
    image: mongo
    volumes:
      - mongodb_kapp:/data/db
    networks:
      - kapp

volumes:
  mongodb_kapp:

networks:
  kapp:
